services:
  ctrace:
    build: .
    image: ctrace
    container_name: ctrace
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro

      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /sys/fs/bpf:/sys/fs/bpf

      - /var/run/docker.sock:/var/run/docker.sock:ro
